apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-afdian-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: baseUrl
          label: 爱发电访问地址
          placeholder: 请输入爱发电访问地址（末尾不带/）
          validation: required
          help: 启用后必填
          value: https://afdian.com
        - $formkit: text
          name: token
          label: 用户token
          placeholder: 请输入用户TOKEN
          validation: required
          help: 启用后必填，在 https://afdian.com/dashboard/dev 中 API TOKEN 获取
        - $formkit: text
          name: userId
          label: 用户ID
          placeholder: 请输入用户ID
          validation: required
          help: 启用后必填，在 https://afdian.com/dashboard/dev 中 user_id 获取
        - $formkit: text
          name: username
          label: 用户名
          value: username
          placeholder: 请输入爱发电登录用户名，如果不输入用户名和密码，获取赞助方案等接口会出现异常
          help: 如果不输入用户名和密码，获取赞助方案等接口会出现异常
        - $formkit: password
          name: password
          label: 密码
          value: password
          placeholder: 请输入爱发电登录用户密码，如果不输入用户名和密码，获取赞助方案等接口会出现异常
          help: 如果不输入用户名和密码，获取赞助方案等接口会出现异常
    - group: themeSetting
      label: 赞赏展示页设置
      formSchema:
        - $formkit: text
          name: rewardTopTitle
          label: 标题文字
          placeholder: 请输入文字内容
          value: 感谢我的赞赏者们
        - $formkit: text
          name: sponsorUrl
          label: 赞助地址
          value: https://afdian.com/a/carolcoral
          placeholder: 请输入跳转赞助地址
          validation: required
          help: 启用后必填，否则爱发电页面可能会报错
        - $formkit: text
          name: sponsorNumber
          label: 切换赞助金额显示颜色值
          value: 66
          placeholder: 请输入需要切换颜色的赞助金额限制
          help: 非必填，默认切换赞助金额颜色的金额值为 66
        - $formkit: select
          name: themeStyle
          id: themeStyle
          key: themeStyle
          label: 赞助展示页面样式
          value: afdian
          options:
            - label: 默认展示页面
              value: afdian
            - label: 顶图样式
              value: afdian2
            - label: 滚动样式
              value: afdian3
        - $formkit: radio
          name: enableRewardRoll
          id: enableRewardRoll
          key: enableRewardRoll
          label: 顶部图片展示
          if: $get(themeStyle).value == 'afdian2'
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: url
          name: rewardTopImgUrl
          label: 顶部图片URL
          if: $get(themeStyle).value == 'afdian2' && $get(enableRewardRoll).value
          placeholder: 请输入顶部图片地址
          value: https://youimg1.c-ctrip.com/target/100m1b000001bj6if96CC.jpg
        - $formkit: radio
          name: enableTheme3Img
          id: enableTheme3Img
          key: enableTheme3Img
          label: 背景图片设置
          if: $get(themeStyle).value == 'afdian3'
          value: false
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: url
          name: theme3ImgUrl
          label: 背景图片URL
          if: $get(themeStyle).value == 'afdian3' && $get(enableTheme3Img).value
          placeholder: 请输入背景图片URL
          value: https://youimg1.c-ctrip.com/target/100m1b000001bj6if96CC.jpg
    - group: shop
      label: 商品页设置
      formSchema:
        - $formkit: select
          name: themeStyle
          id: themeStyle
          key: themeStyle
          label: 商品展示页面样式
          value: shop1
          options:
            - label: 默认展示页面
              value: shop1
            - label: 爱发电官网样式
              value: shop2
        - $formkit: text
          name: basic_title
          label: 爱发电商品页大标题
          placeholder: 请输入爱发电商品页大标题
          if: $get(themeStyle).value == 'shop1'
          validation: required
          help: 启用后必填
          value: 爱发电商品展示
        - $formkit: text
          name: second_title
          label: 爱发电商品页副标题
          placeholder: 请输入爱发电商品页副标题
          if: $get(themeStyle).value == 'shop1'
          validation: required
          help: 启用后必填
          value: services