apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-afdian-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: token
          label: 用户token
          placeholder: 请输入用户TOKEN
          help: 启用后必填，在 https://afdian.net/dashboard/dev 中 API TOKEN 获取
        - $formkit: text
          name: userId
          label: 用户ID
          placeholder: 请输入用户ID
          help: 启用后必填，在 https://afdian.net/dashboard/dev 中 user_id 获取