apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-afdian-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: text
          name: token
          label: 用户token
          placeholder: 请输入用户TOKEN
          validation: required
          help: 启用后必填，在 https://afdian.net/dashboard/dev 中 API TOKEN 获取
        - $formkit: text
          name: userId
          label: 用户ID
          placeholder: 请输入用户ID
          validation: required
          help: 启用后必填，在 https://afdian.net/dashboard/dev 中 user_id 获取
    - group: themeSetting
      label: 赞赏展示页设置
      formSchema:
        - $formkit: text
          name: rewardTopTitle
          label: 标题文字
          placeholder: 请输入文字内容
          value: 感谢我的赞赏者们
        - $formkit: text
          name: sponsorUrl
          label: 赞助地址
          value: https://afdian.net/a/carolcoral
          placeholder: 请输入跳转赞助地址
          validation: required
          help: 启用后必填，否则爱发电页面可能会报错
        - $formkit: text
          name: sponsorNumber
          label: 切换赞助金额显示颜色值
          value: 66
          placeholder: 请输入需要切换颜色的赞助金额限制
          help: 非必填，默认切换赞助金额颜色的金额值为 66
        - $formkit: select
          name: themeStyle
          id: themeStyle
          key: themeStyle
          label: 赞助展示页面样式
          value: afdian
          options:
            - label: 默认展示页面
              value: afdian
            - label: 顶图样式
              value: afdian2
            - label: 滚动样式
              value: afdian3
        - $formkit: radio
          name: enableRewardRoll
          id: enableRewardRoll
          key: enableRewardRoll
          label: 顶部图片展示
          if: $get(themeStyle).value == 'afdian2'
          value: true
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: url
          name: rewardTopImgUrl
          label: 顶部图片URL
          if: $get(themeStyle).value == 'afdian2' && $get(enableRewardRoll).value
          placeholder: 请输入顶部图片地址
          value: https://youimg1.c-ctrip.com/target/100m1b000001bj6if96CC.jpg
        - $formkit: radio
          name: enableTheme3Img
          id: enableTheme3Img
          key: enableTheme3Img
          label: 背景图片设置
          if: $get(themeStyle).value == 'afdian3'
          value: false
          options:
            - label: 启用
              value: true
            - label: 禁用
              value: false
        - $formkit: url
          name: theme3ImgUrl
          label: 背景图片URL
          if: $get(themeStyle).value == 'afdian3' && $get(enableTheme3Img).value
          placeholder: 请输入背景图片URL
          value: https://youimg1.c-ctrip.com/target/100m1b000001bj6if96CC.jpg